In [1]:
import numpy as np
we = np.array([0.5, 0.2, -0.7])
light = np.array([[1, 0, 1], [1, 1, 1], [0, 1, 1], [1, 1, 1], [0, 1, 1], [0, 0, 1]])
tr = np.array([0, 1, 1, 1, 1, 0])
a = 0.05
print(light[0].dot(we))
for i in range(402):
    awe = 0
    for j in range(len(light)):
        pred = light[j].dot(we)
        awe += (pred - tr[j])**2
        dif = pred - tr[j]
        we -= dif * a * light[j]
print(we)
print(light[1].dot(we))

-0.19999999999999996
[ 6.59301712e-09  1.00000001e+00 -1.43323905e-08]
1.000000006175253


In [2]:
np.random.seed(1)
def relu(x):
    return (x > 0) * x
a = 0.2
h = 4
light = np.array([[1, 0, 1], [0, 1, 1], [1, 1, 1], [0, 0, 1]])
tr = np.array([0, 1, 1, 0]).T
we_0_1 = 2 * np.random.random((3, h)) - 1
we_1_2 = 2 * np.random.random((h, 1)) - 1
l_0 = light[0]
l_1 = relu(np.dot(l_0, we_0_1))
l_2 = np.dot(l_1, we_1_2)

In [3]:
np.random.seed(1)
def relu(x):
    return (x > 0) * x
def relu2deriv(out):
    return out > 0
a = 0.2
h = 4
light = np.array([[1, 0, 1], [0, 1, 1], [1, 1, 1], [0, 0, 1]])
tr = np.array([0, 1, 1, 0]).T
we_0_1 = 2 * np.random.random((3, h)) - 1
we_1_2 = 2 * np.random.random((h, 1)) - 1
for i in range(60):
    l2er = 0
    for j in range(len(light)):
        l0 = light[j:j + 1]
        l1 = relu(np.dot(l0, we_0_1))
        l2 = np.dot(l1, we_1_2)
        l2er += np.sum((l2 - tr[j:j+1])**2)
        l2dif = tr[j:j+1] - l2
        l1dif = l2dif.dot(we_1_2.T)*relu2deriv(l1)
        we_1_2 += a * l1.T.dot(l2dif)
        we_0_1 += a * l0.T.dot(l1dif)
    if (i%10 == 9):
        print(l2er)
l0 = light[1]
l1 = relu(np.dot(l0, we_0_1))
l2 = np.dot(l1, we_1_2)
print(l2)

0.48325399402457136
0.05837999254467696
0.004900543636095845
0.0003197155102200634
2.0108892939533896e-05
1.3866974108713296e-06
[1.00068639]


In [7]:
import numpy as np
np.random.seed(1)
def relu(x):
    return (x > 0) * x
def relu2deriv(out):
    return out > 0
l = np.array([[1, 0, 1], [0, 1, 1], [0, 0, 1], [1, 1, 1]])
tr = np.array([0, 1, 0, 1]).T
a = 0.05
h = 3
w01 = 2 * np.random.random((3, h)) - 1
w12 = 2 * np.random.random((h, 1)) - 1
l0 = l[0:1]
l1 = np.dot(l0, w01)
l1 = relu(l1)
l2 = np.dot(l1, w12)
err = (l2 - tr[0:1])**2
l2d = (l2 - tr[0:1])
l1d = l2d.dot(w12.T)
l1d *= relu2deriv(l1)
wd12 = l1.T.dot(l2d)
wd01 = l0.T.dot(l1d)
w12 -= a * wd12
w01 -= a * wd01

In [25]:
import numpy as np
np.random.seed(1)
def relu(x):
    return (x > 0) * x
def relu2deriv(out):
    return out > 0
data = np.array([[0, 1, 1, 0, 0, 1, 0, 0, 1], [1, 1, 0, 0, 1, 0, 0, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1, 0], [1, 1, 1, 0, 1, 0, 1, 1, 1]])
tr = np.array([[0, 1, 0], [0, 1, 0], [1, 0, 0], [0, 0, 1]])
a = 0.05
h = 15
w01 = 2 * np.random.random((9, h)) - 1
w12 = 2 * np.random.random((h, 3)) - 1
for i in range(500):
    for j in range(len(data)):
        l0 = data[j:j+1]
        l1 = relu(np.dot(l0, w01))
        l2 = np.dot(l1, w12)
        l2d = (l2 - tr[j:j+1])
        l1d = l2d.dot(w12.T)
        l1d *= relu2deriv(l1)
        wd12 = l1.T.dot(l2d)
        wd01 = l0.T.dot(l1d)
        w12 -= a * wd12
        w01 -= a * wd01
l0 = np.array([0, 1, 1, 
               0, 0, 1, 
               0, 0, 1])
l1 = relu(np.dot(l0, w01))
print(np.dot(l1, w12))

[1.11022302e-16 1.00000000e+00 8.32667268e-17]


In [33]:
import numpy as np
np.random.seed(1)
def relu(x):
    return (x > 0) * x
def relu2deriv(out):
    return out > 0
data = np.array([[0, 0, 0, 0, 1,
                  0, 0, 0, 1, 1,
                  0, 0, 0, 0, 1,
                  0, 0, 0, 0, 1,
                  0, 0, 0, 0, 1],
                 [0, 0, 0, 0, 1,
                  0, 0, 0, 0, 1,
                  0, 0, 0, 0, 1,
                  0, 0, 0, 0, 1,
                  0, 0, 0, 0, 1],
                 [0, 0, 0, 1, 0,
                  0, 0, 1, 1, 0,
                  0, 0, 0, 1, 0,
                  0, 0, 0, 1, 0,
                  0, 0, 0, 1, 0],
                 [0, 0, 0, 1, 0,
                  0, 0, 0, 1, 0,
                  0, 0, 0, 1, 0,
                  0, 0, 0, 1, 0,
                  0, 0, 0, 1, 0],
                 [0, 0, 1, 0, 0,
                  0, 0, 1, 0, 0,
                  0, 0, 1, 0, 0,
                  0, 0, 1, 0, 0,
                  0, 0, 1, 0, 0],
                 [0, 0, 1, 0, 0,
                  0, 1, 1, 0, 0,
                  0, 0, 1, 0, 0,
                  0, 0, 1, 0, 0,
                  0, 0, 1, 0, 0],
                 [0, 0, 1, 0, 0,
                  0, 1, 0, 1, 0,
                  0, 1, 0, 1, 0,
                  0, 1, 0, 1, 0,
                  0, 0, 1, 0, 0],
                 [0, 0, 0, 1, 0,
                  0, 0, 1, 0, 1,
                  0, 0, 1, 0, 1,
                  0, 0, 1, 0, 1,
                  0, 0, 0, 1, 0],
                 [0, 1, 0, 0, 0,
                  1, 0, 1, 0, 0,
                  1, 0, 1, 0, 0,
                  1, 0, 1, 0, 0,
                  0, 1, 0, 0, 0],
                 [0, 1, 1, 1, 0,
                  0, 0, 0, 1, 0,
                  0, 0, 1, 0, 0,
                  0, 1, 0, 0, 0,
                  0, 1, 1, 1, 0]])
tr = np.array([[0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [0, 0, 1]])
a = 0.05
h = 15
w01 = 2 * np.random.random((25, h)) - 1
w12 = 2 * np.random.random((h, 3)) - 1
for i in range(500):
    for j in range(len(data)):
        l0 = data[j:j+1]
        l1 = relu(np.dot(l0, w01))
        l2 = np.dot(l1, w12)
        l2d = (l2 - tr[j:j+1])
        l1d = l2d.dot(w12.T)
        l1d *= relu2deriv(l1)
        wd12 = l1.T.dot(l2d)
        wd01 = l0.T.dot(l1d)
        w12 -= a * wd12
        w01 -= a * wd01
l0 = np.array([0, 0, 1, 1, 0,
               0, 0, 0, 1, 0,
               0, 0, 0, 1, 0,
               0, 0, 0, 1, 0,
               0, 0, 0, 1, 0])
l1 = relu(np.dot(l0, w01))
print(np.round(np.dot(l1, w12), decimals=2))

[ 0.28  1.   -0.05]


In [6]:
import numpy as np
np.random.seed(1)
def relu(x):
    return (x > 0) * x
def relu2deriv(out):
    return out > 0
data = np.array([[0,0,0,0,1,
                  0,0,0,1,1,
                  0,0,0,0,1,
                  0,0,0,0,1,
                  0,0,0,0,1],
                 [0, 0, 0, 0, 1,
                  0, 0, 0, 0, 1,
                  0, 0, 0, 0, 1,
                  0, 0, 0, 0, 1,
                  0, 0, 0, 0, 1],
                 [0, 0, 0, 1, 0,
                  0, 0, 1, 1, 0,
                  0, 0, 0, 1, 0,
                  0, 0, 0, 1, 0,
                  0, 0, 0, 1, 0],
                 [0, 0, 0, 1, 0,
                  0, 0, 0, 1, 0,
                  0, 0, 0, 1, 0,
                  0, 0, 0, 1, 0,
                  0, 0, 0, 1, 0],
                 [0, 0, 1, 0, 0,
                  0, 0, 1, 0, 0,
                  0, 0, 1, 0, 0,
                  0, 0, 1, 0, 0,
                  0, 0, 1, 0, 0],
                 [0, 0, 1, 0, 0,
                  0, 1, 1, 0, 0,
                  0, 0, 1, 0, 0,
                  0, 0, 1, 0, 0,
                  0, 0, 1, 0, 0],
                 [0, 0, 1, 0, 0,
                  0, 1, 0, 1, 0,
                  0, 1, 0, 1, 0,
                  0, 1, 0, 1, 0,
                  0, 0, 1, 0, 0],
                 [0, 0, 0, 1, 0,
                  0, 0, 1, 0, 1,
                  0, 0, 1, 0, 1,
                  0, 0, 1, 0, 1,
                  0, 0, 0, 1, 0],
                 [0, 1, 0, 0, 0,
                  1, 0, 1, 0, 0,
                  1, 0, 1, 0, 0,
                  1, 0, 1, 0, 0,
                  0, 1, 0, 0, 0],
                 [0, 1, 1, 1, 0,
                  0, 0, 0, 1, 0,
                  0, 0, 1, 0, 0,
                  0, 1, 0, 0, 0,
                  0, 1, 1, 1, 0],
                 [0,0,1,1,1,
                  0,0,0,0,1,
                  0,0,0,1,0,
                  0,0,1,0,0,
                  0,0,1,1,1],
                 [1,1,1,0,0,
                  0,0,1,0,0,
                  0,1,0,0,0,
                  1,0,0,0,0,
                  1,1,1,0,0]])
tr = np.array([[0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0], [0, 0, 1], [0, 0, 1], [0, 0, 1]])
a = 0.05
h1 = 15
h2 = 15
w01 = 2 * np.random.random((25, h1)) - 1
w12 = 2 * np.random.random((h1, h2)) - 1
w23 = 2 * np.random.random((h2, 3)) - 1
for i in range(500):
    for j in range(len(data)):
        l0 = data[j:j+1]
        l1 = relu(np.dot(l0, w01))
        l2 = relu(np.dot(l1, w12))
        l3 = np.dot(l2, w23)
        l3d = (l3 - tr[j:j+1])
        l2d = l3d.dot(w23.T)
        l2d *= relu2deriv(l2)
        l1d = l2d.dot(w12.T)
        l1d *= relu2deriv(l1)
        wd23 = l2.T.dot(l3d)
        wd12 = l1.T.dot(l2d)
        wd01 = l0.T.dot(l1d)
        w23 -= a * wd23
        w12 -= a * wd12
        w01 -= a * wd01
l0 = np.array([0, 0, 1, 1, 1,
               0, 0, 0, 0, 1,
               0, 0, 0, 1, 0,
               0, 0, 1, 0, 0,
               0, 0, 1, 1, 1])
l1 = relu(np.dot(l0, w01))
l2 = relu(np.dot(l1, w12))
print(np.round(np.dot(l2, w23), decimals=2))

[0. 0. 1.]


In [14]:
import numpy as np

np.random.seed(1)

def relu(x):
  return (x > 0) * x
def relu2deriv(ou):
  return ou > 0

data = np.array([[0,0,0,0,1,
                  0,0,0,1,1,
                  0,0,0,0,1,
                  0,0,0,0,1,
                  0,0,0,0,1],
                 [0,0,0,0,1,
                  0,0,0,0,1,
                  0,0,0,0,1,
                  0,0,0,0,1,
                  0,0,0,0,1],
                 [0,0,1,0,0,
                  0,1,0,1,0,
                  0,1,0,1,0,
                  0,1,0,1,0,
                  0,0,1,0,0]])
g = np.array([[0,1], [0,1], [1,0]])
h = 25
we01 = 2 * np.random.random((25, h)) - 1
we12 = 2 * np.random.random((h, 2)) - 1
a = 0.005

for i in range(100):
  for j in range(len(g)):
    l0 = data[j:j+1]
    l1 = relu(np.dot(l0, we01))
    l2 = np.dot(l1, we12)
    l2d = l2 - g[j:j + 1]
    l1d = l2d.dot(we12.T)
    l1d *= relu2deriv(l1)
    l0d = l1d.dot(we01.T)
    l0d *= relu2deriv(l0)
    wd12 = l1.T.dot(l2d)
    wd01 = l0.T.dot(l1d)
    we12 -= wd12 * a
    we01 -= wd01 * a
  l0 = np.array([ 0,0,1,0,0,
                  0,1,0,1,0,
                  0,1,0,1,0,
                  0,1,0,1,0,
                  0,0,1,0,0])
  l1 = relu(np.dot(l0, we01))
  print(np.dot(l1, we12))

[-1.09805422 -1.65781067]
[-0.30370808 -1.26673176]
[ 0.1398479  -0.97272811]
[ 0.40122888 -0.7523945 ]
[ 0.56348013 -0.58650823]
[ 0.66944138 -0.46039251]
[ 0.74196616 -0.36336257]
[ 0.7936742  -0.28781238]
[ 0.831808   -0.22835346]
[ 0.8607028  -0.18114164]
[ 0.88306958 -0.14339494]
[ 0.90067782 -0.11306311]
[ 0.91472909 -0.08860569]
[ 0.92606815 -0.0688438 ]
[ 0.93530662 -0.0528605 ]
[ 0.94289798 -0.03993293]
[ 0.94918502 -0.02948508]
[ 0.95453514 -0.02113913]
[ 0.95951126 -0.01482636]
[ 0.96380488 -0.00991988]
[ 0.96739103 -0.00604091]
[ 0.97034878 -0.00294512]
[ 9.72783850e-01 -4.64297914e-04]
[0.97479759 0.00152414]
[0.97647669 0.00311363]
[0.97789154 0.00437765]
[0.97909777 0.00537526]
[0.98013883 0.00615451]
[0.98104841 0.00675478]
[0.98185265 0.00720852]
[0.98257186 0.00754247]
[0.98322183 0.00777872]
[0.98381495 0.00793547]
[0.98436091 0.00802773]
[0.98486742 0.00806788]
[0.98534057 0.00806608]
[0.98578523 0.0080307 ]
[0.98620533 0.00796859]
[0.98660402 0.00788536]
[0.9869838